[package]
cairo-version = "2.6.3"
name = "stark_sailor_v1"
version = "1.0.0"

[cairo]
sierra-replace-ids = true

[scripts]

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.7.4" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/starksailor-v5/katana"
# Default account for katana with seed = 0s
account_address = "0x496eedbe97001c5553da4dafea2a1d87078cbad8fffc84431a1127c6cf15628"
private_key = "0x11a6d11e1f66858f1306821b9f10d04004a61d28bda6e9b5f2310385c0ccc1f"
# world_address = "" # Update this line with your world address

# [profile.dev.tool.dojo.env]
# rpc_url = "https://api.cartridge.gg/x/starksailor-v2-2/katana"
# account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
# private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
# world_address = "0x79ea98421d7f7804564626129eceec1cc952b1106361ca4a6b25a4939cf9e82"

[tool.dojo.world]
name = "Stark Sailor"
description = "Stark Sailor - Explore, Discover, Battle on Starknet's oceanic playground."
cover_uri = "https://assets.starksailor.net/starksailor/upload/cover.png"
icon_uri = "https://assets.starksailor.net/starksailor/upload/icon.png"
website = "https://starksailor.net/"

[tool.dojo.world.socials]
x = "https://twitter.com/playStarkSailor"
discord = "https://discord.gg/tCwW6Tph"
github = "https://github.com/starksailor/Stark-Sailor"
telegram = "https://t.me/dojoengine"
